#!/usr/bin/env python3
"""Generate ``ci-constraints.txt`` from vingapi's ``requirements.lock`` (opsalert#34).

CI installs this library under the third-party pins prod runs, so a gate run
tests the versions vingapi deploys rather than whatever PyPI resolves that day.

Usage:
    scripts/sync_ci_constraints.py <path-to-lock> --sha <vingapi-sha> [--check] [--out <path>]

Without ``--check`` it writes the constraints file (default: the repo-root
``ci-constraints.txt``). With ``--check`` it writes nothing and exits 1 with a
unified diff of the pins when the tracked file differs from the lock, 0 when
they match. A missing lock or constraints file exits 2. Stdlib only.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "ci-constraints.txt"

_PIN = re.compile(r"^[A-Za-z0-9_.\-]+==\S+$")

REGENERATE = (
    "python scripts/sync_ci_constraints.py <vingapi requirements.lock> --sha <vingapi commit sha>"
)


def third_party_pins(lock_text: str) -> list[str]:
    """Every ``name==version`` line of the lock, in lock order, unchanged.

    Editable lines (``-e ...``), other option lines (``--...``), comments and
    blank lines are dropped.
    """
    return [line for line in lock_text.splitlines() if _PIN.match(line)]


def render(lock_text: str, source_sha: str) -> str:
    header = [
        "# Generated by scripts/sync_ci_constraints.py; do not edit by hand.",
        f"# Source: vingapi requirements.lock @ {source_sha}",
        f"# Regenerate: {REGENERATE}",
    ]
    return "\n".join(header + third_party_pins(lock_text)) + "\n"


def unrecognized_lines(lock_text: str) -> list[str]:
    """Lines that are neither a pin nor an excluded kind (blank, comment, ``-`` option).

    A pin carrying an environment marker or a hash would land here instead of
    being dropped silently.
    """
    return [
        line
        for line in lock_text.splitlines()
        if line.strip() and not line.lstrip().startswith(("#", "-")) and not _PIN.match(line)
    ]


def _pins_of_constraints(text: str) -> list[str]:
    return [line for line in text.splitlines() if line and not line.startswith("#")]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("lock", type=Path, help="path to vingapi requirements.lock")
    parser.add_argument("--sha", required=True, help="vingapi commit sha the lock was read at")
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 with a diff when the tracked pins differ from the lock",
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="constraints file path")
    args = parser.parse_args(argv)

    if not args.lock.is_file():
        print(f"sync_ci_constraints: lock file not found: {args.lock}", file=sys.stderr)
        return 2
    lock_text = args.lock.read_text(encoding="utf-8")
    unknown = unrecognized_lines(lock_text)
    if unknown:
        print(f"sync_ci_constraints: unrecognized lines in {args.lock}: {unknown}", file=sys.stderr)
        return 2
    expected = third_party_pins(lock_text)
    if not expected:
        print(f"sync_ci_constraints: no name==version pins in {args.lock}", file=sys.stderr)
        return 2

    if args.check:
        if not args.out.is_file():
            print(f"sync_ci_constraints: constraints file not found: {args.out}", file=sys.stderr)
            return 2
        tracked = _pins_of_constraints(args.out.read_text(encoding="utf-8"))
        if tracked == expected:
            print(f"sync_ci_constraints: {args.out} matches {args.lock} ({len(expected)} pins)")
            return 0
        diff = difflib.unified_diff(
            tracked, expected, fromfile=str(args.out), tofile=str(args.lock), lineterm=""
        )
        print("\n".join(diff))
        print(
            f"sync_ci_constraints: {args.out} differs from {args.lock}; regenerate with: "
            f"{REGENERATE}",
            file=sys.stderr,
        )
        return 1

    args.out.write_text(render(lock_text, args.sha), encoding="utf-8")
    print(f"sync_ci_constraints: wrote {args.out} ({len(expected)} pins, vingapi @ {args.sha})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
